#!/bin/bash

######################################################################
##             DigitalOcean Droplet - Basic Set Up Script           ##
#######################################################################
# To loginto a droplet from WSL ==> ssh root@<IP>
# to create a alias to the droplet:-
#  example alias do3='ssh -i myssh1 root@ipv4'" >> .bashrc
# first install curl ==> apt install curl -y
# then:-
# dpkg --configure -a -y  --> experimental!!
# then:-
# curl -k -s https://raw.githubusercontent.com/leighton-0/DigitalOcean_Droplet_Setup/main/main_1 | bash
# This script installs the following:-
#   git
#   ???
#   python3 & piphttps://github.com/leighton-0/DigitalOcean_Droplet_Setup/edit/main/main
#   standard aliases
#   wget
#   tmux with a custom config file --> towry/tmux-config used
#   nmap
#   standard build essentials
#   nano text editor from binaries with custom
#   ruby
#   dnsutils                     # dig & nslookup
#   whois                        # github reference site https://github.com/rfc1036/whois
#   dpkg - Debian package management system

# to install:-
#   need to first install curl ==> apt install curl
#   then
#   curl -k -s https://raw.githubusercontent.com/leighton-0/DigitalOcean_Droplet_Setup/main/main_1 | bash

s=3                  # Slows scritpt down so you can see whats going on

printf '\n============================================================\n'
printf '[+] Updating System\n'
printf '============================================================\n\n'
sleep $s
apt update -y
apt upgrade -y
sleep $s
<<SHELL_MULTI_LINE_COMMENTS
# if [ 1 -eq 0 ]; then        # BLOCK COMMNENT
# dpkg --configure -a -y

apt install wget -y
apt install ruby -y
apt install git -y
apt install tmux -y
git clone https://github.com/towry/tmux-config.git
./tmux-config/install.sh
apt install build-essential libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev  libgmp-dev zlib1g-dev -y
sleep $s
apt install nmap -y
apt install whois -y
apt install dnsutils -y
apt install tree
apt install figlet toilet            # install figlet for banners

wget https://raw.githubusercontent.com/FreedomBen/digall/main/digall && chmod +x digall
# installs an automated script for dig
# Ref:- https://github.com/FreedomBen/digall
# Use :- ./digall example.com

printf '\n============================================================\n'
printf '[+]  Upload standard .bash_aliases & upgrades to .bashrc. \n'
printf '============================================================\n\n'
sleep $s

if [ ! -f ~/.bashrc.bak ]; then                                                      # Check if bashrc.bak has already been copied. If yes then skip
    cp /root/.bashrc /root/.bashrc.bak                                               # bak Up bashrc incase I fuck it up

wget https://raw.githubusercontent.com/leighton-0/.dotfiles/main/.bash_aliases       # Upload my standard aliases file

cat <<EOF >.bashrc                                                                #Add pointer to new .bash_aliases
if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi
EOF

. .bashrc && . .bash_aliases                                                         #source .bashrc & .bash_aliases

printf '\n============================================================\n'
printf '[+]  Install nano text editor from binaries. \n'
printf '============================================================\n\n'
sleep $s
wget https://www.nano-editor.org/dist/v7/nano-7.2.tar.gz
tar -zxvf nano-7.2.tar.gz
cd nano-7.2
sudo apt install libncurses-dev
./configure
make
make install
# set up colour text ref:- https://askubuntu.com/questions/90013/how-do-i-enable-syntax-highlighting-in-nano
find /usr/share/nano/ -iname "*.nanorc" -exec echo include {} \; >> ~/.nanorc

#     python3 seems ot be installed by default on debian but not pip3 it seems!!
# apt-get install python3.11.2

#     get error ==> "error: externally-managed-environment" when try & install pip. rectify with:-
cd /usr/lib/python3.11
rm EXTERNALLY-MANAGED
cd ~
apt install python3-pip

printf '\n============================================================\n'
printf '[+]  Install docker \n'
print '[+] link --> https://docs.docker.com/engine/install/debian/#install-using-the-repository \n'
printf '============================================================\n\n'
sleep $s
# Add Docker's official GPG key:
apt-get update
apt-get install ca-certificates curl gnupg
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update

# install docker package
apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Verify that the installation is successful by running the hello-world image:
docker run hello-world
sleep $s
printf '\n============================================================\n'
printf '[+]  Install golang 1.21.1 \n'
printf '============================================================\n\n'
sleep $s
apt-get update
wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
tar -xvf go1.21.0.linux-amd64.tar.gz
mv go /usr/local
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
source ~/.profile
# ref:- https://royzsec.medium.com/install-go-1-21-0-in-ubuntu-22-04-2-in-5-minutes-468a5330c64e

printf '\n============================================================\n'
printf '[+]  Install projectdiscovery subfinder \n'
printf '============================================================\n\n'
sleep $s
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest

echo export PATH=$PATH:$HOME/go/bin >> $home/.bashrc
source $home/.bashrc
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest

printf '\n============================================================\n'
printf '[+]  Install WPScan \n'
printf '============================================================\n\n'
sleep $s
apt install build-essential libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev  libgmp-dev zlib1g-dev -y
sleep 5
gem install wpscan                                  #install wpscan
SHELL_MULTI_LINE_COMMENTS
#printf '\n============================================================\n'
#printf '[+]  Install Proxychains ref'- https://github.com/SagaOfAGuy/proxychains-config/tree/main \n'
#printf '============================================================\n\n'
sleep $s
wget https://raw.githubusercontent.com/leighton-0/DigitalOcean_Droplet_Setup/main/proxychains_config.sh
chmod +x proxychains_config.sh
./proxychains_config.sh
sleep $s

printf '\n============================================================\n'
printf '[+]  Upgrade DigitalOcean Metrics Agent \n'
printf '============================================================\n\n'
sleep $s
# Ref https://docs.digitalocean.com/products/monitoring/how-to/upgrade-legacy-agent/
# Uninstall the legacy metrics agent.
apt purge do-agent
# Install the current metrics agent
curl -sSL https://repos.insights.digitalocean.com/install.sh -o /tmp/install.sh
# run the installation using Bash:
bash /tmp/install.sh
# fi            # END BLOCK COMMENT

apt autoremove

# source ~/.bashrc && source ~/.bash_aliases

echo "THE END"


